server:
  port: 8082

spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://notification-db:5432/notificationdb
    username: notification_user
    password: notification_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
